inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.4

Rails:
  Enabled: true

Documentation:
  Enabled: false

Lint/SuppressedException:
  Exclude:
    - Rakefile

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/ModuleLength:
  Exclude:
    - 'app/models/countries.rb'

Style/RescueModifier:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ExpandPathArguments:
  Exclude:
    - 'Rakefile'
    - 'config.ru'

Rails/UnknownEnv:
  Exclude:
    - 'config/initializers/govuk_admin_template.rb'
