sudo: false
language: ruby
services:
  - redis-server
cache:
  bundler: true
  directories:
  - node_modules
  - vendor/assets/bower_components
node_js:
- '0.10'
notifications:
  slack:
    secure: sWqa2Zgj4C+MceW25svEpX+pEDUOPAVgPcFkR9gKOTlw67UWueBXh/bvxfUpG8vb89fDbVEA7ddpnTJMWt1iSOSLyY4x/BrMIJahOrsSsACjqVL98J5wsgdy1AGC8mZ/2vra6E5ZIT4TN0BAebIoa9Vtwr/0jmIGtBuVKjA9n/SwRQ3enFsRrl4hqUfYnk919CuRckM9lCy2Fku2nFCDCCHPXCS6+p0JBiFnRi/TLmUIxUPm+IpOsW0Wox2v5JL4k7WSLqijAPwdg9L24xWwrSCs40dACBrppZR6QqUV3mQdLj23J0psX+42Y+TL8x9FpKVGu1AJAooZvAH6BImInUrcopbYuIG0xumVzjtObBa93BiUFLz0DEibYmjR/r3fS7o6+C4OmSrfIMHlfzLNMvQG5q6NkPMuAbgF/7gQebZ6IKMu4rlwKW84JojgXdxYi7Hs0iiutRsfCV74AXniYRQGG4lhLPTNuaiPCXCkc86AiGIAOKZBXIjcbAu5oLpRIw/R24qdQaeqnK0wnswlT+mRtNGIrLY1pCs6FfpekU+Lv/x3LqUw/odlwsJozy5giR69iw1vVdPG5jKl8QyiqgLFdHZB1M7MW1jHj8zFqzCEgr+Mnj+3xeoIC+5ZhoxxyaoiARcy1OSyxiZAvBxuq/LpygKqzYwlHm2X6dF8qwQ=
branches:
  except:
  - "/^prototypes\\/.*$/"
addons:
  postgresql: 9.4
before_install:
- gem update --system
- gem install bundler -v=1.16.2
before_script:
- npm install
- bundle exec rake db:setup RAILS_ENV=test
