sudo: false
language: ruby
cache:
  bundler: true
  directories:
  - node_modules
  - vendor/assets/bower_components
node_js:
- '0.10'
notifications:
  slack:
    secure: sWqa2Zgj4C+MceW25svEpX+pEDUOPAVgPcFkR9gKOTlw67UWueBXh/bvxfUpG8vb89fDbVEA7ddpnTJMWt1iSOSLyY4x/BrMIJahOrsSsACjqVL98J5wsgdy1AGC8mZ/2vra6E5ZIT4TN0BAebIoa9Vtwr/0jmIGtBuVKjA9n/SwRQ3enFsRrl4hqUfYnk919CuRckM9lCy2Fku2nFCDCCHPXCS6+p0JBiFnRi/TLmUIxUPm+IpOsW0Wox2v5JL4k7WSLqijAPwdg9L24xWwrSCs40dACBrppZR6QqUV3mQdLj23J0psX+42Y+TL8x9FpKVGu1AJAooZvAH6BImInUrcopbYuIG0xumVzjtObBa93BiUFLz0DEibYmjR/r3fS7o6+C4OmSrfIMHlfzLNMvQG5q6NkPMuAbgF/7gQebZ6IKMu4rlwKW84JojgXdxYi7Hs0iiutRsfCV74AXniYRQGG4lhLPTNuaiPCXCkc86AiGIAOKZBXIjcbAu5oLpRIw/R24qdQaeqnK0wnswlT+mRtNGIrLY1pCs6FfpekU+Lv/x3LqUw/odlwsJozy5giR69iw1vVdPG5jKl8QyiqgLFdHZB1M7MW1jHj8zFqzCEgr+Mnj+3xeoIC+5ZhoxxyaoiARcy1OSyxiZAvBxuq/LpygKqzYwlHm2X6dF8qwQ=
branches:
  except:
  - "/^prototypes\\/.*$/"
addons:
  postgresql: 9.4
before_script:
- "./bin/rake db:setup RAILS_ENV=test"
- npm install
deploy:
  provider: heroku
  app: staging-locator-pensionwise
  api_key:
    secure: YSFobVg9yj/PGEhKkvDaswmOj0jusBDc+9+VDswrg2OUAT0OYL6ypV8Sk/wtzhSDDysbMrq5mWwlG+886lWqYgF6WJyhy5syrqaqPrvHNx7lTq3mWTpSbM545kXcI923cP1Rx7rgzlvCVNVRYgnoIryAMrFaeeqYfMpBC2Zg0aRFCFlSYhdmuVdXQB1es/QfyqlT7rlzNWdg/B8LLkuAj4b9wkFj0tmjYK0zD59aC4MoZyWn9iNyiu73Uwx0+Vqcak0RNmLVLTeYKIlhrz4Oswzq5KJmTxclEmJrhTE4AS8YcJzA2NSbQ/6XHq2//XsrOIHva0FtkvwByDfnP3dFc/zARLS+hu5Jm+JdNCyBZiwJKu10yCgCnvfkLio4C1iPY5U+m90VRMhMEP3m2Y3PmohEOmyeG1PxWg4nEYdRIJcMW5rcyExiNArAyO+QjIUAZSXMpqg1CQTIWJjh5LOIP9JgYmIauvl19OFRdbfq31XwgjXphZaOl2aeU5Aw3lNmK5N/H145LVlVxuKup8bjdzFzO+sYG+2Wsg2FuR9yTYDv3raCTFK6yDp7dWvoiM90dZ8hxtwCWz5Ohs/h5nUJCAytq7NEUYswB+bIHtuBXsF+CqaBTLkHRFRz7j+EkUbNXid6Xyh9A0+YNJh4LtQcV/idmA+OJgCxkY9D4T+M6bA=
  on:
    repo: guidance-guarantee-programme/location-register
  run: curl -X POST -d '' https://ggp-smoke-tests.herokuapp.com/staging
