default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: location-register_development

test: &test
  <<: *default
  database: location-register_test

production: &production
  <<: *default
  database: location-register_production
  username: location-register
  password: <%= ENV['LOCATION-REGISTER_DATABASE_PASSWORD'] %>

staging:
  <<: *production
